name: A workflow for Hello World
on: push
jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Agron"
